#!/usr/bin/env python3
"""Generate lightweight LaTeX figure and table fragments from report outputs.

The fragments use only standard LaTeX picture primitives plus xcolor, so the
paper remains portable across the local fallback build and the Cambridge
template path.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CAMPAIGN_CSV = ROOT / "reports" / "constitutional-review-campaign-v2.csv"
CALIBRATION_CSV = ROOT / "reports" / "calibration-baseline.csv"
SWEEP_CSV = ROOT / "reports" / "parameter-sweep-v4.csv"
MECHANISM_CSV = ROOT / "reports" / "mechanism-ablation-v2.csv"
FIGURE_DIR = ROOT / "paper" / "figures"
TABLE_DIR = ROOT / "paper" / "tables"

SELECTED_SCENARIOS = [
    ("current-us-like", "Current"),
    ("term-limited-balanced", "18-year"),
    ("emergency-restraint-court", "No-gap"),
    ("nonpartisan-commission", "Commission"),
    ("supermajority-review", "60 pct"),
    ("panel-en-banc", "Panel"),
    ("comparative-constitutional-senates", "16-seat"),
    ("cross-checking-courts", "Cross-check"),
]

FIELDS = [
    "directionalScore",
    "legalStability",
    "rightsProtection",
    "partisanAlignment",
    "shadowDocketAbuse",
    "emergencyLegitimacyRisk",
    "constitutionalConflict",
    "democraticResponsiveness",
    "administrativeCost",
    "publicConfidence",
    "rightsDomainClaimantSuccess",
    "structuralDomainClaimantSuccess",
    "electionDomainClaimantSuccess",
    "executivePowerDomainClaimantSuccess",
    "administrativeDomainClaimantSuccess",
    "economicDomainClaimantSuccess",
]


def fmt(value: float) -> str:
    return f"{value:.1f}"


def tex_escape(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


def fmt3(value: float) -> str:
    return f"{value:.3f}"


def clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def read_weighted_averages() -> dict[str, dict[str, float]]:
    totals: dict[str, defaultdict[str, float]] = defaultdict(lambda: defaultdict(float))
    weights: dict[str, float] = defaultdict(float)
    with CAMPAIGN_CSV.open(newline="") as handle:
        for row in csv.DictReader(handle):
            key = row["scenarioKey"]
            weight = float(row.get("caseWeight") or 1.0)
            weights[key] += weight
            for field in FIELDS:
                if row.get(field):
                    totals[key][field] += float(row[field]) * weight
    return {
        key: {field: totals[key][field] / weights[key] for field in FIELDS}
        for key in totals
    }


def write_conflict_confidence_tradeoff(averages: dict[str, dict[str, float]]) -> None:
    left, bottom, width, height = 24.0, 16.0, 86.0, 54.0
    x_min, x_max = 0.35, 0.41
    y_min, y_max = 0.38, 0.64
    offsets = {
        "current-us-like": (-13.0, 3.0, "r"),
        "term-limited-balanced": (-9.0, 7.0, "r"),
        "emergency-restraint-court": (4.0, 7.0, "l"),
        "nonpartisan-commission": (-6.0, 3.0, "r"),
        "supermajority-review": (-11.0, -4.0, "r"),
        "panel-en-banc": (4.0, 3.0, "l"),
        "comparative-constitutional-senates": (-15.0, 5.0, "r"),
        "cross-checking-courts": (-4.0, -7.0, "r"),
    }
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begingroup",
        "\\setlength{\\unitlength}{1mm}",
        "\\begin{picture}(128,82)",
        "\\scriptsize",
    ]
    for tick in (0.35, 0.37, 0.39, 0.41):
        x = left + ((tick - x_min) / (x_max - x_min)) * width
        lines.extend([
            f"\\put({fmt(x)},{fmt(bottom)}){{\\color{{black!15}}\\line(0,1){{{fmt(height)}}}}}",
            f"\\put({fmt(x)},{fmt(bottom - 3.2)}){{\\makebox(0,0){{{tick:.2f}}}}}",
        ])
    for tick in (0.40, 0.46, 0.52, 0.58, 0.64):
        y = bottom + ((tick - y_min) / (y_max - y_min)) * height
        lines.extend([
            f"\\put({fmt(left)},{fmt(y)}){{\\color{{black!15}}\\line(1,0){{{fmt(width)}}}}}",
            f"\\put({fmt(left - 4.0)},{fmt(y)}){{\\makebox(0,0)[r]{{{tick:.2f}}}}}",
        ])
    lines.extend([
        f"\\put({fmt(left)},{fmt(bottom)}){{\\line(1,0){{{fmt(width)}}}}}",
        f"\\put({fmt(left)},{fmt(bottom)}){{\\line(0,1){{{fmt(height)}}}}}",
    ])
    for key, label in SELECTED_SCENARIOS:
        values = averages[key]
        x = left + ((values["constitutionalConflict"] - x_min) / (x_max - x_min)) * width
        y = bottom + ((values["publicConfidence"] - y_min) / (y_max - y_min)) * height
        x = max(left, min(left + width, x))
        y = max(bottom, min(bottom + height, y))
        shade = 15 + round(clamp01(values["shadowDocketAbuse"] / 0.25) * 70)
        color = "red" if key == "current-us-like" else f"black!{shade}"
        marker = 3.1 if key == "current-us-like" else 2.5
        dx, dy, anchor = offsets[key]
        label_color = "red" if key == "current-us-like" else "black"
        lines.extend([
            f"\\put({fmt(x - marker / 2.0)},{fmt(y - marker / 2.0)}){{\\color{{{color}}}\\rule{{{marker:.1f}mm}}{{{marker:.1f}mm}}}}",
            f"\\put({fmt(x + dx)},{fmt(y + dy)}){{\\makebox(0,0)[{anchor}]{{\\color{{{label_color}}}{label}}}}}",
        ])
    lines.extend([
        f"\\put({fmt(left + width / 2.0)},{fmt(4.5)}){{\\makebox(0,0){{Constitutional conflict $\\downarrow$}}}}",
        f"\\put({fmt(left - 5.0)},{fmt(bottom + height + 5.0)}){{\\makebox(0,0)[l]{{Public confidence $\\uparrow$}}}}",
        "\\put(58.0,76.0){\\makebox(0,0)[l]{Marker shade increases with shadow-docket abuse.}}",
        "\\put(58.0,71.8){\\makebox(0,0)[l]{No-gap = merits follow-through; 16-seat = senate court.}}",
        "\\end{picture}",
        "\\endgroup",
        "",
    ])
    (FIGURE_DIR / "conflict_confidence_tradeoff.tex").write_text("\n".join(lines))


def write_emergency_profile(averages: dict[str, dict[str, float]]) -> None:
    left_label, left_axis, scale = 31.0, 35.0, 82.0
    top, row_gap, bar_gap = 66.0, 7.2, 1.65
    metrics = [
        ("shadowDocketAbuse", "Shadow abuse", "black!75"),
        ("emergencyLegitimacyRisk", "Emerg. legit. risk", "black!45"),
        ("publicConfidence", "Public confidence", "black!18"),
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begingroup",
        "\\setlength{\\unitlength}{1mm}",
        "\\begin{picture}(128,80)",
        "\\scriptsize",
    ]
    for tick in (0.0, 0.2, 0.4, 0.6):
        x = left_axis + tick * scale
        lines.extend([
            f"\\put({fmt(x)},{fmt(8.0)}){{\\color{{black!15}}\\line(0,1){{62.0}}}}",
            f"\\put({fmt(x)},{fmt(4.7)}){{\\makebox(0,0){{{tick:.1f}}}}}",
        ])
    for row_index, (key, label) in enumerate(SELECTED_SCENARIOS):
        values = averages[key]
        y = top - row_index * row_gap
        label_color = "red" if key == "current-us-like" else "black"
        lines.append(f"\\put({fmt(left_label)},{fmt(y)}){{\\makebox(0,0)[r]{{\\color{{{label_color}}}{label}}}}}")
        for metric_index, (field, _metric_label, color) in enumerate(metrics):
            bar_color = ("red!80", "red!55", "red!25")[metric_index] if key == "current-us-like" else color
            bar_y = y + (1 - metric_index) * bar_gap
            value = max(0.0, averages[key][field])
            lines.append(
                f"\\put({fmt(left_axis)},{fmt(bar_y)}){{\\color{{{bar_color}}}\\rule{{{max(value * scale, 0.35):.1f}mm}}{{1.1mm}}}}"
            )
    legend_x = 38.0
    for index, (_field, label, color) in enumerate(metrics):
        x = legend_x + index * 29.0
        lines.extend([
            f"\\put({fmt(x)},{fmt(74.0)}){{\\color{{{color}}}\\rule{{5.0mm}}{{1.8mm}}}}",
            f"\\put({fmt(x + 7.0)},{fmt(74.3)}){{\\makebox(0,0)[l]{{{label}}}}}",
        ])
    lines.extend([
        "\\put(76.0,1.0){\\makebox(0,0){Raw normalized campaign average}}",
        "\\end{picture}",
        "\\endgroup",
        "",
    ])
    (FIGURE_DIR / "emergency_profile.tex").write_text("\n".join(lines))


def heat_color(value: float, scale_max: float, current: bool = False) -> tuple[str, str]:
    shade = 8 + round(clamp01(value / scale_max) * 72)
    color = f"red!{shade}" if current else f"black!{shade}"
    text = "white" if shade >= 54 else "black"
    return color, text


def write_domain_claimant_success(averages: dict[str, dict[str, float]]) -> None:
    columns = [
        ("rightsDomainClaimantSuccess", "Rights"),
        ("structuralDomainClaimantSuccess", "Struct."),
        ("electionDomainClaimantSuccess", "Elect."),
        ("executivePowerDomainClaimantSuccess", "Exec."),
        ("administrativeDomainClaimantSuccess", "Admin."),
        ("economicDomainClaimantSuccess", "Econ."),
    ]
    left_label = 38.0
    left = 44.0
    top = 60.0
    cell_w = 13.5
    cell_h = 5.1
    row_gap = 6.3
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begingroup",
        "\\setlength{\\unitlength}{1mm}",
        "\\begin{picture}(128,72)",
        "\\scriptsize",
    ]
    for col_index, (_field, label) in enumerate(columns):
        x = left + col_index * cell_w
        lines.append(f"\\put({fmt(x + cell_w / 2.0)},{fmt(66.0)}){{\\makebox(0,0){{\\textbf{{{label}}}}}}}")
    for row_index, (key, label) in enumerate(SELECTED_SCENARIOS):
        values = averages[key]
        y = top - row_index * row_gap
        label_color = "red" if key == "current-us-like" else "black"
        lines.append(f"\\put({fmt(left_label)},{fmt(y + cell_h / 2.0)}){{\\makebox(0,0)[r]{{\\color{{{label_color}}}{label}}}}}")
        for col_index, (field, _label) in enumerate(columns):
            value = values[field]
            x = left + col_index * cell_w
            fill, text = heat_color(value, 0.55, key == "current-us-like")
            lines.extend([
                f"\\put({fmt(x)},{fmt(y)}){{\\color{{{fill}}}\\rule{{{fmt(cell_w - 0.8)}mm}}{{{fmt(cell_h)}mm}}}}",
                f"\\put({fmt(x + cell_w / 2.0 - 0.4)},{fmt(y + cell_h / 2.0)}){{\\makebox(0,0){{\\color{{{text}}}{value:.2f}}}}}",
            ])
    lines.extend([
        "\\put(72.0,4.0){\\makebox(0,0){Domain-specific claimant-success rates; darker cells are higher.}}",
        "\\end{picture}",
        "\\endgroup",
        "",
    ])
    (FIGURE_DIR / "domain_claimant_success.tex").write_text("\n".join(lines))


def read_calibration_rows() -> list[dict[str, str]]:
    with CALIBRATION_CSV.open(newline="") as handle:
        return list(csv.DictReader(handle))


def write_calibration_guardrails() -> None:
    selected = [
        ("current-merits-transfer", "Merits transfer"),
        ("current-invalidation", "Invalidation"),
        ("current-emergency-applications", "Emergency filings"),
        ("current-shadow-abuse", "Shadow abuse"),
        ("commission-partisan-alignment", "Partisan alignment"),
        ("emergency-restraint-shadow", "Emergency restraint"),
    ]
    rows_by_key = {row["targetKey"]: row for row in read_calibration_rows()}
    source_labels = {
        "deep-research-intake-synthesis": "source register",
        "scdb-modern-2025-01": "SCDB",
        "shadow-docket-v2-0": "shadow database",
        "black-epstein-recusal": "recusal data",
    }

    def source_basis(row: dict[str, str]) -> str:
        source = source_labels.get(row["sourceKey"], row["sourceKey"])
        basis = "model fallback" if row["rangeBasis"] == "fallback" else "source range"
        return f"{source}; {basis}"

    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begin{table}[hbt!]",
        "\\centering",
        "\\caption{Selected calibration guardrails}",
        "\\label{tab:calibration-guardrails}",
        "\\Description{Table showing selected calibration guardrails, their intended use, simulated observations, source-informed ranges, source bases, and status.}",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{1.05in}>{\\raggedright\\arraybackslash}p{0.72in}>{\\raggedright\\arraybackslash}p{0.78in}rr>{\\raggedright\\arraybackslash}p{0.92in}r}",
        "\\toprule",
        "Guardrail & Scenario & Use & Observed & Range & Source basis & Status \\\\",
        "\\midrule",
    ]
    for key, label in selected:
        row = rows_by_key[key]
        scenario = {
            "current-us-like": "Current-like",
            "emergency-restraint-court": "No-gap",
            "nonpartisan-commission": "Commission",
            "legislative-override": "Override",
        }.get(row["scenarioKey"], row["scenario"])
        lines.append(
            f"{tex_escape(label)} & {tex_escape(scenario)} & "
            f"{tex_escape(row['guardrailClass'].replace('_', ' '))} & "
            f"{float(row['observed']):.3f} & "
            f"{float(row['min']):.3f}--{float(row['max']):.3f} & "
            f"{tex_escape(source_basis(row))} & {'within' if row['pass'] == 'true' else 'review'} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    (TABLE_DIR / "calibration_guardrails.tex").write_text("\n".join(lines))


def read_sweep_rows() -> dict[str, dict[str, str]]:
    with SWEEP_CSV.open(newline="") as handle:
        return {row["scenarioKey"]: row for row in csv.DictReader(handle)}


def write_uncertainty_bands(averages: dict[str, dict[str, float]]) -> None:
    sweep = read_sweep_rows()
    selected = [
        ("term-limited-balanced", "18-year terms"),
        ("emergency-restraint-court", "No emergency merits gap"),
        ("current-us-like", "Current-like"),
        ("nonpartisan-commission", "Commission"),
        ("constitutional-council", "Constitutional council"),
        ("dual-supreme-courts", "Dual supreme courts"),
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begin{table}[hbt!]",
        "\\centering",
        "\\caption{Campaign scores and uncertainty bands for selected designs}",
        "\\label{tab:uncertainty-bands}",
        "\\Description{Table comparing campaign averages with named-prior uncertainty bands for directional score, shadow-docket abuse, and constitutional conflict.}",
        "\\footnotesize",
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{1.65in}rrrr}",
        "\\toprule",
        "Scenario & Campaign score & Score 5/50/95 & Shadow 5/50/95 & Conflict 5/50/95 \\\\",
        "\\midrule",
    ]
    for key, label in selected:
        row = sweep[key]
        lines.append(
            f"{tex_escape(label)} & {fmt3(averages[key]['directionalScore'])} & "
            f"{float(row['directionalP05']):.3f}/{float(row['directionalMedian']):.3f}/{float(row['directionalP95']):.3f} & "
            f"{float(row['shadowDocketAbuseP05']):.3f}/{float(row['shadowDocketAbuseMedian']):.3f}/{float(row['shadowDocketAbuseP95']):.3f} & "
            f"{float(row['constitutionalConflictP05']):.3f}/{float(row['constitutionalConflictMedian']):.3f}/{float(row['constitutionalConflictP95']):.3f} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    (TABLE_DIR / "uncertainty_bands.tex").write_text("\n".join(lines))


def read_mechanism_rows() -> list[dict[str, str]]:
    with MECHANISM_CSV.open(newline="") as handle:
        return list(csv.DictReader(handle))


def write_mechanism_summary() -> None:
    fields = [
        "deltaDirectional",
        "deltaRightsProtection",
        "deltaShadowDocketAbuse",
        "deltaConstitutionalConflict",
        "deltaDemocraticResponsiveness",
        "deltaAdministrativeCost",
    ]
    selected = [
        "term-regularization",
        "appointment-screening",
        "emergency-restraint",
        "invalidation-threshold",
        "panel-routing",
        "cross-checking-court",
        "dual-court-filter",
        "constitutional-council",
        "legislative-override",
    ]
    totals: dict[str, defaultdict[str, float]] = defaultdict(lambda: defaultdict(float))
    weights: dict[str, float] = defaultdict(float)
    names: dict[str, str] = {}
    for row in read_mechanism_rows():
        key = row["mechanismKey"]
        names[key] = row["mechanism"]
        weight = float(row.get("caseWeight") or 1.0)
        weights[key] += weight
        for field in fields:
            totals[key][field] += float(row[field]) * weight

    def average(key: str, field: str) -> float:
        return totals[key][field] / weights[key]

    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begin{table}[hbt!]",
        "\\centering",
        "\\caption{Mechanism-level paired contrasts against the current-like design}",
        "\\label{tab:mechanism-summary}",
        "\\Description{Table of weighted average paired contrasts for institutional mechanisms against the current-like design across campaign assumption cases.}",
        "\\footnotesize",
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{1.58in}rrrrrr}",
        "\\toprule",
        "Mechanism & Score & Rights & Shadow & Conflict & Respons. & Admin. cost \\\\",
        "\\midrule",
    ]
    for key in selected:
        lines.append(
            f"{tex_escape(names[key])} & "
            f"{average(key, 'deltaDirectional'):+.3f} & "
            f"{average(key, 'deltaRightsProtection'):+.3f} & "
            f"{average(key, 'deltaShadowDocketAbuse'):+.3f} & "
            f"{average(key, 'deltaConstitutionalConflict'):+.3f} & "
            f"{average(key, 'deltaDemocraticResponsiveness'):+.3f} & "
            f"{average(key, 'deltaAdministrativeCost'):+.3f} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    (TABLE_DIR / "mechanism_summary.tex").write_text("\n".join(lines))


def main() -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    averages = read_weighted_averages()
    write_conflict_confidence_tradeoff(averages)
    write_emergency_profile(averages)
    write_domain_claimant_success(averages)
    write_calibration_guardrails()
    write_uncertainty_bands(averages)
    write_mechanism_summary()


if __name__ == "__main__":
    main()
