package constitutionalreview.model;


public enum AccessPath
{
	DISCRETIONARY_CERTIORARI,
	PAID_CERTIORARI,
	IFP_CERTIORARI,
	DIRECT_CONSTITUTIONAL_COMPLAINT,
	AMPARO,
	FILTERED_QPC,
	COURT_REFERRAL_CONCRETE_REVIEW,
	ABSTRACT_EX_ANTE_REVIEW,
	ABSTRACT_EX_POST_REVIEW,
	INTERBRANCH_DISPUTE,
	ELECTORAL_REVIEW,
	EMERGENCY_APPLICATION
}
