package constitutionalreview.model;

public record ReviewCase(
        String id,
        CaseType type,
        DocketType docketType,
        AccessPath accessPath,
        ReviewTiming reviewTiming,
        PetitionType petitionType,
        double legalAmbiguity,
        double rightsBurden,
        double democraticMandate,
        double partisanSalience,
        double lawIdeology,
        double emergencyPressure,
        double requestedEmergencyRelief,
        double executiveDefianceRisk,
        double legislativeQuality,
        double constitutionalConflictPotential,
        double publicAttention,
        double overridePressure,
        double lowerCourtConflict,
        double lowerCourtErrorRisk,
        double certiorariPressure,
        double solicitorGeneralSignal,
        int amicusBriefs,
        double splitMaturity,
        int relistCount,
        boolean specialistCounsel,
        double vehicleDefectRisk,
        double conditionalReversalProbability,
        EmergencyApplication emergencyApplication
) {
    public ReviewCase withId(String id) {
        return new ReviewCase(
                id,
                type,
                docketType,
                accessPath,
                reviewTiming,
                petitionType,
                legalAmbiguity,
                rightsBurden,
                democraticMandate,
                partisanSalience,
                lawIdeology,
                emergencyPressure,
                requestedEmergencyRelief,
                executiveDefianceRisk,
                legislativeQuality,
                constitutionalConflictPotential,
                publicAttention,
                overridePressure,
                lowerCourtConflict,
                lowerCourtErrorRisk,
                certiorariPressure,
                solicitorGeneralSignal,
                amicusBriefs,
                splitMaturity,
                relistCount,
                specialistCounsel,
                vehicleDefectRisk,
                conditionalReversalProbability,
                emergencyApplication
        );
    }
}
