package constitutionalreview.institution;


public enum AppointmentMethod
{
	PRESIDENT_SENATE,
	NONPARTISAN_COMMISSION,
	LEGISLATIVE_SUPERMAJORITY,
	JUDICIAL_ELECTORATE,
	LOTTERY_FROM_APPELLATE_POOL,
	ROTATING_PANEL
}
