package constitutionalreview.institution;


public enum EmergencyDocketRule
{
	OPEN_EMERGENCY,
	REASONED_FAST_TRACK,
	SUPERMAJORITY_STAY,
	NO_RELIEF_WITHOUT_MERITS,
	MANDATORY_WRITTEN_REASONING,
	AUTOMATIC_MERITS_FOLLOW_UP
}
