package constitutionalreview.institution;


public enum OverrideOutcome
{
	NONE,
	FAILED,
	RIGHTS_CARVEOUT_BLOCKED,
	ORDINARY_SUPERMAJORITY,
	DELAYED_REENACTMENT,
	REFERENDUM_APPROVAL,
	REPEATED_OVERRIDE
}
