package constitutionalreview.institution;


public enum OverrideRule
{
	NONE,
	LEGISLATIVE_SUPERMAJORITY,
	DELAYED_REENACTMENT,
	POPULAR_REFERENDUM,
	LEGISLATIVE_WINDOW,
	JURISDICTION_STRIPPING_CONSTRAINT
}
